version: '3.1'
services:
  app:
    build: docker
    volumes:
      - .:/app:delegated
      - ./docker/supervisor.conf.d/:/etc/supervisor/conf.d
      - ./docker/nginx.default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /app
    ports:
      - "8000:80"
#      - "9000:9000"
#      - "9003:9003"
    environment:
      - XDEBUG_MODE=debug
      - PHP_IDE_CONFIG=serverName=app
      - XDEBUG_CONFIG=client_host=host.docker.internal idekey=PHPSTORM
